name: insula
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 
  generate: true

  fonts:
    - family: SplineSans  # kodda çağırılacak isim.
      fonts:
        - asset: assets/fonts/SplineSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SplineSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SplineSans-Bold.ttf
          weight: 700

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
